[[sites]]
name="pastebin"
url="https://pastebin.com/"

[[sites]]
name="rust"
url="https://www.rust-lang.org/"

[[sites]]
name="gtk"
url="https://www.gtk.org"

[[sites]]
name="notification test"
url="https://www.bennish.net/web-notifications.html"

[[sites]]
name="epochconverter"
url="https://www.epochconverter.com/"