dark_mode=true

[[sites]]
name="rust"
url="https://www.rust-lang.org/"
dark_mode=false

[[sites]]
name="about:blank"
url="about:blank"
dark_mode=false

[[sites]]
name="gtk"
url="https://www.gtk.org"
dark_mode=true

[[sites]]
name="notification test"
url="https://www.bennish.net/web-notifications.html"

[[sites]]
name="epochconverter"
url="https://www.epochconverter.com/"